[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "gold-price-prediction"
version = "1.0.0"
description = "Gold Price Prediction using Machine Learning"
requires-python = ">=3.9"